export const currentOperator = '麻醉医师 刘医生';

export const dictionaries = {
  recordStatuses: ['草稿', '记录中', '待签名', '已签名', '待归档', '已归档', '抢救中', '修改中'],
  collectStatuses: ['未连接', '待启动', '采集中', '采集暂停', '采集异常', '已结束'],
  asaLevels: ['I级', 'II级', 'III级', 'IV级', 'V级'],
  anesthesiaMethods: ['全身麻醉', '椎管内麻醉', '静脉麻醉', '神经阻滞麻醉', '复合麻醉'],
  airwayMethods: ['面罩通气', '喉罩', '气管插管', '双腔管', '气管切开', '其他'],
  intubationMethods: ['直接喉镜', '视频喉镜', '纤支镜', '快速诱导', '清醒插管'],
  extubationStatuses: ['顺利', '呛咳', '喉痉挛', '低氧', '延迟拔管', '带管入 PACU/ICU'],
  destinations: ['PACU', 'ICU', '病房', '其他'],
  eventTypes: ['入室', '启动记录', '设备采集', '麻醉开始', '诱导', '插管', '穿刺', '手术开始', '用药', '输液', '输血', '异常生命体征', '抢救', '抢救结束', '手术结束', '拔管', '出室', '签名', '修改', '其他'],
  medicationNames: ['丙泊酚', '舒芬太尼', '瑞芬太尼', '罗库溴铵', '依托咪酯', '咪达唑仑', '去甲肾上腺素', '阿托品', '地塞米松', '麻黄碱', '多巴胺', '肾上腺素'],
  frequencyOptions: [1, 3, 5, 10, 15],
  fieldActions: ['填入当前时间', '复制字段', '清空字段', '使用常用值', '定位质控问题'],
};

export const capabilityMap = [
  { name: '麻醉记录单结构化录入', status: '已具备', location: '患者信息 / 麻醉记录' },
  { name: '术中生命体征连续记录', status: '已具备', location: '生命体征' },
  { name: '麻醉机/监护仪/输注泵采集占位', status: '前端占位', location: '设备状态卡' },
  { name: '术中用药闭环记录', status: '已具备', location: '用药出入量' },
  { name: '高警示药品双人核对', status: '已具备', location: '质控签名' },
  { name: '异常生命体征自动识别', status: '已具备', location: '生命体征 / 右侧质控' },
  { name: '抢救模式提高记录频率', status: '已具备', location: '顶部操作栏' },
  { name: '气道管理关键节点记录', status: '已具备', location: '气道与事件' },
  { name: '插管/拔管时间节点追溯', status: '已具备', location: '麻醉记录 / 事件时间线' },
  { name: '离室复苏交接记录', status: '已具备', location: '复苏离室' },
  { name: '完整性检查与质控提醒', status: '已具备', location: '质控签名 / 右侧面板' },
  { name: '电子签名后只读', status: '已具备', location: '质控签名' },
  { name: '修改申请与留痕', status: '已具备', location: '质控签名' },
  { name: '结构化 JSON 查看', status: '已具备', location: '预览归档' },
  { name: '归档 PDF/OFD 占位', status: '前端占位', location: '预览归档' },
  { name: '共享调阅占位', status: '前端占位', location: '预览归档' },
];

const deviceTemplate = (collectStatus = '未连接') => ({
  monitor: collectStatus === '采集中' ? '采集中' : collectStatus === '已结束' ? '已结束' : '未连接',
  anesthesiaMachine: collectStatus === '采集中' ? '采集中' : collectStatus === '已结束' ? '已结束' : '未连接',
  infusionPump: collectStatus === '采集中' ? '已连接' : collectStatus === '已结束' ? '已结束' : '未连接',
  dataSource: collectStatus === '采集中' ? '手工录入 + 设备采集占位' : '手工录入',
  collectStatus,
  lastCollectTime: collectStatus === '采集中' ? '09:35' : '',
  collectFrequency: '5分钟/次',
  receiveStatus: collectStatus === '采集中' ? '接收正常' : '未接收',
  abnormalNote: '',
  logs: [
    { time: '08:45', content: '启动采集' },
    { time: '08:50', content: '接收监护仪数据' },
    { time: '08:55', content: '接收麻醉机数据' },
    { time: '09:05', content: '手工修正 SpO2' },
  ],
});

const baseRecord = ({
  status,
  collectStatus,
  method,
  startedAt = '',
  frequency = 5,
  rescueActive = false,
  rescueSummary = null,
}) => ({
  status,
  startedAt,
  dataSource: collectStatus === '采集中' ? '手工录入 + 设备采集占位' : '手工录入',
  vitalFrequency: rescueActive ? 1 : frequency,
  previousFrequency: frequency,
  qualityResults: [],
  modificationLogs: [],
  operationLogs: [
    { time: '08:00', operator: currentOperator, action: '打开麻醉记录单', source: '系统生成' },
  ],
  anesthesia: {
    method,
    inRoomTime: '',
    recordStart: startedAt,
    anesthesiaStart: '',
    inductionStart: '',
    intubationTime: '',
    punctureTime: '',
    blockFinishTime: '',
    surgeryStart: '',
    surgeryEnd: '',
    extubationTime: '',
    anesthesiaEnd: '',
    outRoomTime: '',
    pacuInTime: '',
    pacuOutTime: '',
    anesthesiologist: '刘医生',
    surgeon: '周主任',
    circulatingNurse: '赵护士',
    scrubNurse: '钱护士',
    anesthesiaLevel: '二级',
    inductionNote: '',
    maintenanceNote: '',
    recoveryNote: '',
    specialEventNote: '',
  },
  airway: {
    airwayMethod: method === '全身麻醉' ? '气管插管' : '面罩通气',
    intubationTime: '',
    intubationMethod: '视频喉镜',
    intubationAttempts: 1,
    tubeModel: '',
    tubeDepth: '',
    fixationPosition: '',
    cormack: 'I级',
    difficultAirway: false,
    difficultMeasure: '',
    extubationTime: '',
    extubationStatus: '顺利',
    postExtubationSpo2: '',
    airwayNote: '',
  },
  vitals: [],
  medications: [],
  infusions: [],
  transfusions: [],
  outputs: [],
  events: [],
  recovery: {
    leaveTime: '',
    destination: 'PACU',
    consciousness: '',
    respiration: '',
    circulation: '',
    painScore: 2,
    aldrete: 10,
    tubes: '',
    skin: '',
    handoverNurse: '',
    receiver: '',
    handoverNote: '',
    pacuInTime: '',
    pacuOutTime: '',
    pacuObservations: [],
    pacuVitalSummary: '',
    conclusion: '',
  },
  signatures: {
    anesthesiologist: '',
    surgeon: '',
    nurse: '',
    reviewer: '',
    signedAt: '',
    status: '未签名',
  },
  rescue: {
    active: rescueActive,
    startTime: rescueActive ? '10:18' : '',
    endTime: rescueSummary?.endTime || '',
    summary: rescueSummary,
  },
  device: deviceTemplate(collectStatus),
});

const fullGeneralRecord = () => {
  const record = baseRecord({ status: '记录中', collectStatus: '采集中', method: '全身麻醉', startedAt: '08:20' });
  Object.assign(record.anesthesia, {
    inRoomTime: '08:10',
    anesthesiaStart: '08:22',
    inductionStart: '08:25',
    intubationTime: '08:32',
    surgeryStart: '08:55',
    surgeryEnd: '',
    anesthesiaEnd: '',
    anesthesiologist: '刘医生',
    surgeon: '周主任',
    circulatingNurse: '赵护士',
    scrubNurse: '钱护士',
    inductionNote: '丙泊酚、舒芬太尼、罗库溴铵静脉诱导，诱导平稳。',
    maintenanceNote: '七氟烷复合瑞芬太尼维持，循环基本稳定。',
  });
  Object.assign(record.airway, {
    airwayMethod: '气管插管',
    intubationTime: '08:32',
    tubeModel: '7.5#',
    tubeDepth: '22',
    fixationPosition: '门齿',
  });
  record.vitals = [
    { id: 'v-001-1', time: '08:20', sbp: 138, dbp: 78, hr: 82, rr: 16, spo2: 98, etco2: 36, temp: 36.5, bis: '', remark: '入室', source: '手工录入', abnormalHandled: {} },
    { id: 'v-001-2', time: '08:30', sbp: 126, dbp: 70, hr: 76, rr: 12, spo2: 99, etco2: 34, temp: 36.3, bis: 48, remark: '诱导后', source: '设备采集占位', abnormalHandled: {} },
    { id: 'v-001-3', time: '08:45', sbp: 118, dbp: 66, hr: 72, rr: 12, spo2: 99, etco2: 37, temp: 36.2, bis: 46, remark: '', source: '设备采集占位', abnormalHandled: {} },
    { id: 'v-001-4', time: '09:00', sbp: 112, dbp: 64, hr: 70, rr: 12, spo2: 99, etco2: 38, temp: 36.1, bis: 44, remark: '', source: '设备采集占位', abnormalHandled: {} },
  ];
  record.medications = [
    { id: 'm-001-1', time: '08:25', name: '丙泊酚', dose: 120, unit: 'mg', route: '静脉', reason: '麻醉诱导', executor: '刘医生', checker: '赵护士', highAlert: false, remark: '' },
    { id: 'm-001-2', time: '08:26', name: '舒芬太尼', dose: 20, unit: 'ug', route: '静脉', reason: '镇痛', executor: '刘医生', checker: '赵护士', highAlert: true, remark: '高警示药品双人核对' },
    { id: 'm-001-3', time: '08:27', name: '罗库溴铵', dose: 50, unit: 'mg', route: '静脉', reason: '肌松', executor: '刘医生', checker: '赵护士', highAlert: false, remark: '' },
  ];
  record.infusions = [
    { id: 'i-001-1', time: '08:20', name: '乳酸钠林格液', spec: '500ml', volume: 500, executor: '赵护士' },
    { id: 'i-001-2', time: '09:10', name: '羟乙基淀粉', spec: '500ml', volume: 250, executor: '赵护士' },
  ];
  record.outputs = [
    { id: 'o-001-1', time: '09:30', urine: 120, bloodLoss: 30, drainage: 0, other: 0, remark: '' },
  ];
  record.events = [
    { id: 'e-001-1', time: '08:10', type: '入室', content: '患者入室，核对身份与手术部位', measure: '连接监护，建立静脉通路', recorder: '刘医生', source: '手工补录', remark: '' },
    { id: 'e-001-2', time: '08:20', type: '启动记录', content: '启动麻醉记录', measure: '开始记录术中生命体征、用药及麻醉事件', recorder: '刘医生', source: '系统生成', remark: '' },
    { id: 'e-001-3', time: '08:32', type: '插管', content: '视频喉镜气管插管成功', measure: '确认双肺呼吸音及 EtCO2 波形', recorder: '刘医生', source: '事件触发', remark: '' },
  ];
  return record;
};

const rescueRecord = () => {
  const record = baseRecord({ status: '抢救中', collectStatus: '采集中', method: '全身麻醉', startedAt: '08:05', frequency: 5, rescueActive: true });
  Object.assign(record.anesthesia, {
    inRoomTime: '07:55',
    anesthesiaStart: '08:08',
    inductionStart: '08:12',
    intubationTime: '08:18',
    surgeryStart: '08:45',
    anesthesiologist: '刘医生',
    surgeon: '陈主任',
    circulatingNurse: '吴护士',
    scrubNurse: '郑护士',
    inductionNote: '快速诱导，双腔管置入。',
    maintenanceNote: '静吸复合维持，术中出现低血压和低氧，进入抢救模式。',
    specialEventNote: '10:18 出现 SpO2 下降、血压降低，已启动抢救模式。',
  });
  Object.assign(record.airway, {
    airwayMethod: '双腔管',
    intubationTime: '08:18',
    intubationMethod: '视频喉镜',
    tubeModel: '左 37Fr',
    tubeDepth: '29',
    fixationPosition: '门齿',
    difficultAirway: true,
    difficultMeasure: '视频喉镜辅助，纤支镜确认双腔管位置。',
  });
  record.vitals = [
    { id: 'v-005-1', time: '10:15', sbp: 102, dbp: 58, hr: 108, rr: 12, spo2: 96, etco2: 40, temp: 36.1, bis: 45, remark: '单肺通气', source: '设备采集占位', abnormalHandled: {} },
    { id: 'v-005-2', time: '10:18', sbp: 82, dbp: 46, hr: 128, rr: 8, spo2: 89, etco2: 52, temp: 36.0, bis: 66, remark: '抢救开始', source: '设备采集占位', rescue: true, abnormalHandled: { sbp: '快速补液，去甲肾上腺素泵入', dbp: '循环支持', spo2: '提高 FiO2，复核双腔管位置' } },
    { id: 'v-005-3', time: '10:19', sbp: 88, dbp: 50, hr: 122, rr: 10, spo2: 93, etco2: 48, temp: 36.0, bis: 58, remark: '抢救中', source: '设备采集占位', rescue: true, abnormalHandled: { sbp: '继续血管活性药支持', spo2: '调整通气参数' } },
    { id: 'v-005-4', time: '10:20', sbp: 96, dbp: 56, hr: 116, rr: 12, spo2: 96, etco2: 42, temp: 36.0, bis: 52, remark: '好转', source: '设备采集占位', rescue: true, abnormalHandled: {} },
  ];
  record.medications = [
    { id: 'm-005-1', time: '08:12', name: '依托咪酯', dose: 16, unit: 'mg', route: '静脉', reason: '麻醉诱导', executor: '刘医生', checker: '吴护士', highAlert: false, remark: '' },
    { id: 'm-005-2', time: '10:18', name: '去甲肾上腺素', dose: 8, unit: 'ug/min', route: '泵入', reason: '低血压抢救', executor: '刘医生', checker: '吴护士', highAlert: true, remark: '抢救用药' },
    { id: 'm-005-3', time: '10:19', name: '肾上腺素', dose: 0.1, unit: 'mg', route: '静脉', reason: '循环支持', executor: '刘医生', checker: '吴护士', highAlert: true, remark: '高警示药品' },
  ];
  record.infusions = [
    { id: 'i-005-1', time: '08:05', name: '乳酸钠林格液', spec: '500ml', volume: 500, executor: '吴护士' },
    { id: 'i-005-2', time: '10:18', name: '复方电解质', spec: '500ml', volume: 500, executor: '吴护士' },
  ];
  record.transfusions = [
    { id: 't-005-1', time: '10:22', product: '悬浮红细胞', bagNo: 'B20260517018', bloodType: 'A+', volume: 200, doubleCheck: true, reaction: '无' },
  ];
  record.outputs = [
    { id: 'o-005-1', time: '10:25', urine: 60, bloodLoss: 280, drainage: 30, other: 0, remark: '胸腔引流' },
  ];
  record.events = [
    { id: 'e-005-1', time: '08:05', type: '启动记录', content: '启动麻醉记录', measure: '记录术中生命体征、用药及事件', recorder: '刘医生', source: '系统生成', remark: '' },
    { id: 'e-005-2', time: '10:18', type: '抢救', content: '启动抢救模式', measure: '提高生命体征记录频率，持续观察循环、呼吸及血氧情况', recorder: '刘医生', source: '系统生成', remark: '' },
    { id: 'e-005-3', time: '10:18', type: '异常生命体征', content: 'SpO2 89%，SBP 82mmHg', measure: '调整双腔管位置，提高 FiO2，血管活性药支持', recorder: '刘医生', source: '设备采集占位', remark: '' },
  ];
  return record;
};

const signedRecord = () => {
  const record = baseRecord({
    status: '已签名',
    collectStatus: '已结束',
    method: '静脉麻醉',
    startedAt: '09:05',
    rescueSummary: null,
  });
  Object.assign(record.anesthesia, {
    inRoomTime: '08:55',
    anesthesiaStart: '09:08',
    inductionStart: '09:10',
    surgeryStart: '09:22',
    surgeryEnd: '09:58',
    anesthesiaEnd: '10:05',
    outRoomTime: '10:10',
    pacuInTime: '10:12',
    pacuOutTime: '10:50',
    anesthesiologist: '王医生',
    surgeon: '林医生',
    circulatingNurse: '黄护士',
    scrubNurse: '何护士',
    inductionNote: '静脉麻醉起效平稳。',
    maintenanceNote: '丙泊酚靶控维持。',
    recoveryNote: '术后清醒，呼吸循环平稳。',
  });
  Object.assign(record.airway, {
    airwayMethod: '面罩通气',
    intubationTime: '',
    extubationTime: '',
    extubationStatus: '顺利',
    postExtubationSpo2: 99,
  });
  record.vitals = [
    { id: 'v-004-1', time: '09:05', sbp: 132, dbp: 72, hr: 80, rr: 16, spo2: 98, etco2: 36, temp: 36.4, bis: '', remark: '入室', source: '手工录入', abnormalHandled: {} },
    { id: 'v-004-2', time: '09:30', sbp: 118, dbp: 66, hr: 72, rr: 14, spo2: 99, etco2: 38, temp: 36.3, bis: 50, remark: '', source: '设备采集占位', abnormalHandled: {} },
    { id: 'v-004-3', time: '10:05', sbp: 124, dbp: 70, hr: 76, rr: 16, spo2: 99, etco2: 36, temp: 36.2, bis: 62, remark: '苏醒期', source: '手工修正', abnormalHandled: { bis: '苏醒期 BIS 升高，患者指令反应良好' } },
  ];
  record.medications = [
    { id: 'm-004-1', time: '09:10', name: '丙泊酚', dose: 80, unit: 'mg', route: '静脉', reason: '麻醉诱导', executor: '王医生', checker: '黄护士', highAlert: false, remark: '' },
    { id: 'm-004-2', time: '09:12', name: '瑞芬太尼', dose: 0.1, unit: 'ug/kg/min', route: '泵入', reason: '镇痛维持', executor: '王医生', checker: '黄护士', highAlert: true, remark: '' },
  ];
  record.infusions = [{ id: 'i-004-1', time: '09:05', name: '乳酸钠林格液', spec: '500ml', volume: 300, executor: '黄护士' }];
  record.outputs = [{ id: 'o-004-1', time: '09:58', urine: 0, bloodLoss: 10, drainage: 0, other: 0, remark: '宫腔镜手术' }];
  record.events = [
    { id: 'e-004-1', time: '09:05', type: '启动记录', content: '启动麻醉记录', measure: '开始记录', recorder: '王医生', source: '系统生成', remark: '' },
    { id: 'e-004-2', time: '10:55', type: '签名', content: '提交电子签名', measure: '记录单只读归档前状态', recorder: '王医生', source: '系统生成', remark: '' },
  ];
  Object.assign(record.recovery, {
    leaveTime: '10:10',
    destination: 'PACU',
    consciousness: '清醒',
    respiration: '自主呼吸平稳',
    circulation: '循环稳定',
    aldrete: 10,
    handoverNurse: '黄护士',
    receiver: 'PACU 李护士',
    handoverNote: '交接生命体征、用药和术中特殊情况。',
    pacuInTime: '10:12',
    pacuOutTime: '10:50',
    pacuVitalSummary: 'PACU 期间生命体征平稳。',
    conclusion: '达到离室标准。',
  });
  record.signatures = {
    anesthesiologist: '王医生',
    surgeon: '林医生',
    nurse: '黄护士',
    reviewer: '质控员 陈老师',
    signedAt: '10:55',
    status: '已签名',
  };
  return record;
};

const simpleRecord = ({ status, collectStatus, method, startedAt = '' }) => baseRecord({ status, collectStatus, method, startedAt });

export const initialPatients = [
  {
    id: 'p-001',
    room: 'OR-01',
    name: '张明远',
    gender: '男',
    age: 58,
    height: 170,
    weight: 72,
    inpatientNo: 'ZY20260517001',
    ward: '普外科二病区',
    bedNo: '12床',
    department: '普外科',
    diagnosis: '胆囊结石伴慢性胆囊炎',
    plannedSurgery: '腹腔镜胆囊切除术',
    actualSurgery: '腹腔镜胆囊切除术',
    surgeryDate: '2026-05-17',
    asa: 'II级',
    allergy: '无',
    fasting: '禁食 8 小时，禁饮 4 小时',
    preSpecial: '血压控制可，术前已宣教',
    preVitals: { temp: 36.5, pulse: 82, respiration: 16, bp: '138/78', spo2: 98 },
    riskTags: ['高血压病史'],
    record: fullGeneralRecord(),
  },
  {
    id: 'p-002',
    room: 'OR-02',
    name: '李秋华',
    gender: '女',
    age: 66,
    height: 158,
    weight: 61,
    inpatientNo: 'ZY20260517002',
    ward: '骨科一病区',
    bedNo: '08床',
    department: '骨科',
    diagnosis: '右股骨颈骨折',
    plannedSurgery: '右侧人工股骨头置换术',
    actualSurgery: '右侧人工股骨头置换术',
    surgeryDate: '2026-05-17',
    asa: 'III级',
    allergy: '青霉素过敏',
    fasting: '禁食 10 小时',
    preSpecial: '高龄，合并冠心病，术前心内科会诊',
    preVitals: { temp: 36.7, pulse: 88, respiration: 18, bp: '152/86', spo2: 96 },
    riskTags: ['ASA III', '药物过敏', '高龄'],
    record: simpleRecord({ status: '待签名', collectStatus: '采集暂停', method: '椎管内麻醉', startedAt: '08:35' }),
  },
  {
    id: 'p-003',
    room: 'OR-03',
    name: '王子涵',
    gender: '男',
    age: 7,
    height: 122,
    weight: 24,
    inpatientNo: 'ZY20260517003',
    ward: '小儿外科',
    bedNo: '05床',
    department: '小儿外科',
    diagnosis: '腹股沟斜疝',
    plannedSurgery: '腹腔镜疝囊高位结扎术',
    actualSurgery: '腹腔镜疝囊高位结扎术',
    surgeryDate: '2026-05-17',
    asa: 'I级',
    allergy: '无',
    fasting: '禁食 6 小时，禁饮 2 小时',
    preSpecial: '儿童患者，家属已签署知情同意',
    preVitals: { temp: 36.4, pulse: 96, respiration: 20, bp: '98/62', spo2: 99 },
    riskTags: ['小儿麻醉'],
    record: simpleRecord({ status: '草稿', collectStatus: '未连接', method: '全身麻醉' }),
  },
  {
    id: 'p-004',
    room: 'OR-04',
    name: '赵桂兰',
    gender: '女',
    age: 72,
    height: 156,
    weight: 58,
    inpatientNo: 'ZY20260517004',
    ward: '妇科',
    bedNo: '21床',
    department: '妇科',
    diagnosis: '子宫内膜病变',
    plannedSurgery: '宫腔镜检查术',
    actualSurgery: '宫腔镜检查术',
    surgeryDate: '2026-05-17',
    asa: 'II级',
    allergy: '无',
    fasting: '禁食 8 小时',
    preSpecial: '既往糖尿病，术前血糖 7.8 mmol/L',
    preVitals: { temp: 36.5, pulse: 78, respiration: 16, bp: '132/74', spo2: 98 },
    riskTags: ['高龄', '糖尿病'],
    record: signedRecord(),
  },
  {
    id: 'p-005',
    room: 'OR-05',
    name: '陈建国',
    gender: '男',
    age: 63,
    height: 168,
    weight: 69,
    inpatientNo: 'ZY20260517005',
    ward: '胸外科',
    bedNo: '16床',
    department: '胸外科',
    diagnosis: '右肺上叶结节',
    plannedSurgery: '胸腔镜右肺上叶楔形切除术',
    actualSurgery: '胸腔镜右肺上叶楔形切除术',
    surgeryDate: '2026-05-17',
    asa: 'III级',
    allergy: '无',
    fasting: '禁食 9 小时',
    preSpecial: '肺功能轻度下降，计划双腔管单肺通气',
    preVitals: { temp: 36.6, pulse: 84, respiration: 18, bp: '146/82', spo2: 96 },
    riskTags: ['ASA III', '抢救中', '异常生命体征'],
    record: rescueRecord(),
  },
  {
    id: 'p-006',
    room: 'OR-06',
    name: '孙晓梅',
    gender: '女',
    age: 45,
    height: 162,
    weight: 55,
    inpatientNo: 'ZY20260517006',
    ward: '乳腺外科',
    bedNo: '09床',
    department: '乳腺外科',
    diagnosis: '左乳腺肿物',
    plannedSurgery: '左乳腺肿物切除术',
    actualSurgery: '左乳腺肿物切除术',
    surgeryDate: '2026-05-17',
    asa: 'II级',
    allergy: '无',
    fasting: '禁食 8 小时',
    preSpecial: '术前焦虑，已心理安慰',
    preVitals: { temp: 36.3, pulse: 86, respiration: 16, bp: '126/72', spo2: 99 },
    riskTags: [],
    record: simpleRecord({ status: '记录中', collectStatus: '采集中', method: '全身麻醉', startedAt: '09:10' }),
  },
  {
    id: 'p-007',
    room: 'OR-07',
    name: '周启航',
    gender: '男',
    age: 39,
    height: 176,
    weight: 78,
    inpatientNo: 'ZY20260517007',
    ward: '泌尿外科',
    bedNo: '18床',
    department: '泌尿外科',
    diagnosis: '输尿管结石',
    plannedSurgery: '输尿管镜碎石取石术',
    actualSurgery: '输尿管镜碎石取石术',
    surgeryDate: '2026-05-17',
    asa: 'II级',
    allergy: '无',
    fasting: '禁食 8 小时',
    preSpecial: '术前疼痛已控制',
    preVitals: { temp: 36.8, pulse: 82, respiration: 16, bp: '130/76', spo2: 98 },
    riskTags: ['待归档'],
    record: simpleRecord({ status: '待归档', collectStatus: '已结束', method: '椎管内麻醉', startedAt: '07:50' }),
  },
  {
    id: 'p-008',
    room: 'OR-08',
    name: '刘欣然',
    gender: '女',
    age: 31,
    height: 165,
    weight: 72,
    inpatientNo: 'ZY20260517008',
    ward: '产科',
    bedNo: '03床',
    department: '产科',
    diagnosis: '瘢痕子宫妊娠',
    plannedSurgery: '子宫下段剖宫产术',
    actualSurgery: '子宫下段剖宫产术',
    surgeryDate: '2026-05-17',
    asa: 'II级',
    allergy: '无',
    fasting: '禁食 8 小时',
    preSpecial: '产科急诊备血，胎心监测正常',
    preVitals: { temp: 36.6, pulse: 92, respiration: 18, bp: '128/74', spo2: 99 },
    riskTags: ['产科', '备血'],
    record: simpleRecord({ status: '待签名', collectStatus: '已结束', method: '椎管内麻醉', startedAt: '08:00' }),
  },
];
